### ISSUE TITLE
Installing `climt` and `gfs-dynamical-core`

### ISSUE THREAD

**Issue by adominious** [Ai33L/climt_core#11]
* CliMT version: 0.17.5
* Python version: 3.11
* Operating System: EndeavourOS

I am trying to install both `climt 0.17.5` and `gfs-dynamical-core 0.1.0` using the following two commands
```
pip install climt
pip install gfs-dynamical-core
```

This comes out with the following error message:

```
ERROR: Cannot install climt==0.17.5, gfs-dynamical-core and gfs-dynamical-core==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    gfs-dynamical-core 0.1.0 depends on sympl==0.4.1
    climt 0.17.5 depends on sympl==0.4.0
    gfs-dynamical-core 0.1.0 depends on sympl==0.4.1
    climt 0.16.25 depends on sympl==0.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Is there a safe way of solving this problem, or must I choose a mutual version of `sympl` and risk dependency issues.

**Comment by Ai33L** [comment]
The working version is 0.1.9, please use pip install gfs-dynamical-core==0.1.9

This package works for python 3.8, 3.9 and 3.10 (does not support 3.11 yet). Please use one of these versions of python.

**Comment by adominious** [comment]
When running this command I get the following error, any ideas as to why?

```
ERROR: Could not find a version that satisfies the requirement gfs-dynamical-core==0.1.9 (from versions: 0.1.0, 0.1.1)
ERROR: No matching distribution found for gfs-dynamical-core==0.1.9
```

**Comment by Ai33L** [comment]
Could you let me know which version of python you're using? If you're using python 3.11, then pip cannot find a distribution (pip support exists only for python 3.8, 3.9 and 3.10)

The ideal solution would be to setup and work in a conda environment with one of these versions of python.

**Comment by adominious** [comment]
Apologies I got some of my virtual environments mixed up and was in fact still using python 3.11. I am now using python 3.8. 

I have successfully installed gfs-dynamical-core version 0.1.9, and when trying to install climt, it states this requirement is already satisfied. 

Am I right to assume both have successfully installed?

**Comment by Ai33L** [comment]
Yes, the correct version of climt gets installed automatically with gfs-dynamical-core.

You can also run the held_suarez code in the examples folder to check if things are working okay.

**Comment by adominious** [comment]
This example runs successfully. Thank you for your support.
