### ISSUE TITLE
Finding the primitive equations and model assumtions for `gfs-dynamical-core`

### ISSUE THREAD

**Issue by adominious** [Ai33L/climt_core#16]
* CliMT version: 0.17.12
* gfs version: 0.1.9
* Python version: 3.8.0
* Operating System: EndeavourOS

Not sure if this is the best place to be asking this question, please direct me elsewhere if this is this case.

I wanted to ask about the specific model assumptions that are used within `gfs-dynamical-core`, along with the form of the primitive equations used within the model. Are these readily available somewhere in the source code, or is there some literature online I can view to establish this knowledge?

Thank you in advance.

**Comment by Ai33L** [comment]
Hi, You can find this info in the gfs_dynamical_core/gfsModelDoc.pdf file.
