### ISSUE TITLE
Saving a model state

### ISSUE THREAD

**Issue by amhayes231** [Ai33L/climt_core#18]
Hello, simple question here. Is there a way I can save and reload a model state? Specifically looking at the example `full_radiation_gcm_energy_balanced`, I want to run it for a day, save it, then reinitialize from that day.

**Comment by Ai33L** [comment]
Hi, the easiest way to do this is to save the my_state dictionary to file.  Something like pickle would work well.

To reload model state, just load this dictionary into a variable like X from file and do `my_state.update(X)`. Doing this will update my_state with the saved fields. 

Do the .update() after you've created my_state using get_default_state().
