### ISSUE TITLE
What is the "surface" in GFS

### ISSUE THREAD

**Issue by amhayes231** [Ai33L/climt_core#19]
Hello once again!

Could I ask what the default 'surface' GFSDynamical initialises with please? I have seen some examples where `climt.SlabSurface()` is used, which I assume is initialising with no mountains etc.  I am looking for a more accurate model of a surface map, can you tell me how to achieve this please?

Thank you.

**Comment by Ai33L** [comment]
Hi,

That is correct, SlabSurface does not have realistic land with orography, for instance. I think @JoyMonteiro would know better about implementing realistic features on climt.

**Comment by JoyMonteiro** [comment]
@amhayes231 you can set `surface_geopotential` to any particular topography that you need. See, for example the initial conditions set by the DCMIP component https://github.com/CliMT/climt/blob/develop/climt/_components/dcmip/component.py

you can run the example https://github.com/CliMT/climt/blob/develop/examples/baroclinic_wave.py and inspect the model state.

Note that there is no gravity wave parameterization, so while the flow will respond to the topography, the impact of unresolved gravity waves will not be accounted for. This should not be an issue for idealized model simulations.
