### ISSUE TITLE
Installing gfs_dynamical_core via pip fails

### ISSUE THREAD

**Issue by oculus99** [Ai33L/climt_core#7]
* CliMT version:
* Python version:3.11
* Operating System:Ubuntu 23

### Description

attempt to install directly gfs_dynamical_core
 pip install gfs_dynamical_core fails

### What I Did

```
pip install gfs_dynamical_core
ERROR: Cannot install gfs-dynamical-core==0.1.0 and gfs_dynamical_core because these package versions have conflicting dependencies.

The conflict is caused by:
    gfs-dynamical-core 0.1.0 depends on sympl==0.4.1
    climt 0.17.5 depends on sympl==0.4.0
    gfs-dynamical-core 0.1.0 depends on sympl==0.4.1
    climt 0.16.25 depends on sympl==0.4.0


```

**Comment by Ai33L** [comment]
pip install gfs-dynamical-core should work now. The latest version is 0.1.9, use pip install gfs-dynamical-core==0.1.9 if needed.

The package is released for python 3.8, 3.9 and 3.10. Please use one of these versions of python.
